[env]
host = 10.4.111.209
; 当前运行的测试模块目录，如 ./testcase/vega、./testcase/其他模块
case_file = ./testcase/vega
; 1-清理历史数据，其他-保留历史数据
clean_up = 1
; 仅当此处填写的模块名与 case_file 对应模块一致时执行清理（如 vega）；空或未填则不按模块判断
clean_up_module = vega

[external]
;token = ory_at_UsSybtUejYCwsj6OuQVSxBBYXacJ5BTU8-oWltjXN10.RrEcj_8qvi-t925hZ5sLtnqT7-am--O8yF2_XuN4YTU
token = ory_at_q6oUxO2ZYFSqBaSPD9zzhnc2EPxHqTBj_bHYMR5HVYo.E64c-UaBbRaIjeuhB9fCGyuAlQ-VxoZGjwm7ykk_g6w

[internal]
port = 31098
account_id = 266c6a42-6131-4d62-8f39-853e7093701c
account_type = user
